# Generated by Django 5.1.7 on 2025-04-28 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_rename_name_book_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
